DEF_HELPER_0(fuzzer_forkserver, void)
DEF_HELPER_0(fuzzer_begin, void)
DEF_HELPER_0(fuzzer_end, void)
DEF_HELPER_0(fuzzer_restrict_coverage, void)
DEF_HELPER_0(fuzzer_fetch_testcase, void)
DEF_HELPER_0(fuzzer_kill, void)
DEF_HELPER_0(fuzzer_exit, void)
DEF_HELPER_0(fuzzer_log, void)
DEF_HELPER_1(fuzzer_log_pc, void, i64)
DEF_HELPER_0(fuzzer_send_state_no_revert, void)
DEF_HELPER_0(fuzzer_save_tc, void)
